server {
    listen 8001;  # searxng

    location / {
        auth_basic "auth";
        auth_basic_user_file /etc/nginx/conf.d/.proxy_htpasswd;
        proxy_pass http://172.20.0.3:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    access_log  /var/log/nginx/secsoso_proxy.log;
    error_log  /var/log/nginx/secsoso_proxy.log;
}


upstream ollama {
    server 172.20.0.2:11434;
}

server {
    listen 8002;  # ollama

    location / {
        auth_basic "auth";
        auth_basic_user_file /etc/nginx/conf.d/.proxy_htpasswd;
        proxy_pass http://ollama;
    }

    access_log  /var/log/nginx/secsoso_proxy.log;
    error_log  /var/log/nginx/secsoso_proxy.log;
}

# server {
#     listen 8003;  # appsearch

#     location /api/as/v1/engines/ {
#         proxy_pass http://172.20.0.5:3002;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     location / {
#         add_header Access-Control-Allow-Origin * always;
#         add_header Access-Control-Allow-Headers *;
#         add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS, DELETE";
#         dav_methods PUT DELETE;

#         auth_basic "auth";
#         auth_basic_user_file /etc/nginx/conf.d/.proxy_htpasswd;
#         proxy_pass http://172.20.0.5:3002;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
        
#     }

#     access_log  /var/log/nginx/secsoso_proxy.log;
#     error_log  /var/log/nginx/secsoso_proxy.log;
# }
