allow_es_settings_modification: true
app_search.auth.source: standard
elasticsearch.username: elastic
elasticsearch.password: <CHANGE_ME>
app_search.listen_host: 0.0.0.0
elasticsearch.host: http://elasticsearch:9200
filebeat_log_directory: /var/log/app-search
log_directory: /var/log/app-search
app_search.external_url: http://127.0.0.1:3012/
